### ISSUE TITLE
When swiping to clear a notification, unnecessary text gets shown

### ISSUE THREAD

**Issue by mattp12** [UsrLightmann/Aeaea#3]
When swiping to clear a notification, text gets briefly shown to the left of where clear is shown.

Video: https://streamable.com/ibs58i
Aeaea is the only tweak that's enabled.

iPhone 8 Plus, iOS 13.6.1, checkra1n

**Comment by L1ghtmann** [comment]
Hey,

Just did some tests and this is actually stock behavior. It is just typically hidden and is apparent now only because the alpha is <= .95.
