### ISSUE TITLE
When ColorBanners 3 is enabled, manage, view, and clear change from black and white when swiping a notification

### ISSUE THREAD

**Issue by mattp12** [UsrLightmann/Aeaea#4]
When ColorBanners 3 is enabled and when swiping a notification, the manage, view, and clear text colors change from black and white as you swipe.

Video: https://streamable.com/bqw7ml
Only Aeaea and ColorBanners 3 are enabled.

Edit: this stops happening when changing the content color setting in Aeaea to default. However, with only Aeaea enabled, I can have the content color on black or white with no issues. This also only appears to happen when the content color is black.

iPhone 8 Plus, iOS 13.6.1, checkra1n

**Comment by L1ghtmann** [comment]
Hey,

Based on the video you provided, it looks like ColorBanners may also be setting the text color (since you determined it works fine w only Aeaea). If that is indeed the case, then I'd recommend you turn off the text color option in either ColorBanners or Aeaea, leaving the other enabled.

**Comment by mattp12** [comment]
Oh yeah, I didn't think of ColorBanners having a text color option. I just switched all of those options to stock and everything is resolved now.
